apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: mlserver-mock
spec:
  name: mlserver-mock
  annotations:
    seldon.io/engine-separate-pod: "true"
  protocol: v2
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/mlserver-mock:mock-one
          name: mock-one
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 4Gi
            limits:
              cpu: '4'
              memory: 4Gi
          env:
            - name: MODEL_VARIANT
              value: '0'
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: TASK
              value: automatic-speech-recognition
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "1"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
      replicas: 1
    - spec:
        containers:
        - image: sdghafouri/mlserver-mock:mock-two
          name: mock-two 
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 4Gi
            limits:
              cpu: '4'
              memory: 4Gi
          env:
            - name: MODEL_VARIANT
              value: '0'
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "1"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
      replicas: 1
    graph:
      name: mock-one
      type: MODEL
      children:
      - name: mock-two
        type: MODEL
        children: []
    svcOrchSpec:
      env:
      - name: SELDON_LOG_LEVEL
        value: DEBUG
      resources:
        requests:
          cpu: '4'
          memory: 4Gi
        limits:
          cpu: '4'
          memory: 4Gi
    name: example
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1
