apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: {{ pipeline_name }} 
spec:
  name: {{ pipeline_name }}
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/nlp-pipelines:generalnlp
          name: nlp-3
          imagePullPolicy: Always
          env:
            - name: MODEL_VARIANT
              value: {{ node_1_variant }}
            - name: TRANSFORMERS_CACHE
              value: /app/.cache
            - name: TASK
              value: text-classification
    
    graph:
      name: nlp-3
      type: MODEL
    name: example
    # labels:
    #   sidecar.istio.io/inject: "true"
    replicas: 1
