apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: {{ name }}
spec:
  protocol: v2
  name: {{ name }}
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/nlp-pipelines-mlserver:nlpli
          name: nlp-li
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '{{ cpu_request }}'
              memory: '{{ memory_request }}'
            limits:
              cpu: '{{ cpu_limit }}'
              memory: '{{ memory_limit }}'
          env:
            - name: MODEL_VARIANT
              value: dinalzein/xlm-roberta-base-finetuned-language-identification
            - name: TASK
              value: text-classification
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: '{{ max_batch_size }}'
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: '{{ max_batch_time }}'
      replicas: {{ replicas }}
    - spec:
        containers:
        - image: sdghafouri/nlp-pipelines-mlserver:nlptrans
          name: nlp-trans
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '{{ cpu_request }}'
              memory: '{{ memory_request }}'
            limits:
              cpu: '{{ cpu_limit }}'
              memory: '{{ memory_limit }}'
          env:
            - name: MODEL_VARIANT
              value: {{ model_vairant }}
            - name: TASK
              value: translation_fr_to_en
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: '{{ max_batch_size }}'
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: '{{ max_batch_time }}'
      replicas: {{ replicas }}
    - spec:
        containers:
        - image: sdghafouri/nlp-pipelines-mlserver:nlpsum
          name: nlp-sum
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '{{ cpu_request }}'
              memory: '{{ memory_request }}'
            limits:
              cpu: '{{ cpu_limit }}'
              memory: '{{ memory_limit }}'
          env:
            - name: MODEL_VARIANT
              value: {{ model_vairant }}
            - name: TASK
              value: summarization
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: '{{ max_batch_size }}'
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: '{{ max_batch_time }}'
      replicas: {{ replicas }}
    graph:
      name: nlp-li
      type: MODEL
      children:
      - name: nlp-trans
        type: MODEL
        children:
        - name: nlp-sum
          type: MODEL
          children: []
    svcOrchSpec:
      resources:
        requests:
          cpu: '8'
          memory: 4Gi
        limits:
          cpu: '8'
          memory: 4Gi
    name: example
    # labels:
    #   sidecar.istio.io/inject: "true"
    replicas: 1
