
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: {{ pipeline_name }}
spec:
  name: {{ pipeline_name }} 
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: gcr.io/hale-ivy-335012/audio-sent-pipelines:generalaudio
          name: audio-1
          resources:
            limits:
              cpu: {{cpu_limits}}
            requests:
              cpu: {{cpu_requests}}
          imagePullPolicy: Always
          env:
            - name: MODEL_VARIANT
              value: {{ node_1_variant }}
            - name: TRANSFORMERS_CACHE
              value: /app/.cache
            - name: TASK
              value: automatic-speech-recognition  
    graph:
      name: audio-1
      type: MODEL
    name: example
    # labels:
    #   sidecar.istio.io/inject: "true"
    replicas: 1
