apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: nlp-sum
spec:
  protocol: v2
  name: nlp-sum
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - name: default 
    componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/nlp-pipelines-mlserver:nlpsum
          name: nlp-sum 
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 4Gi
            limits:
              cpu: '4'
              memory: 4Gi
          env:
            - name: MODEL_VARIANT
              value: sshleifer/distilbart-cnn-12-6
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: TASK
              value: summarization
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "5"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
      replicas: 1
    graph:
      name: nlp-sum
      type: MODEL
      children: []
    svcOrchSpec:
      resources:
        requests:
          cpu: '4'
          memory: 4Gi
        limits:
          cpu: '4'
          memory: 4Gi
