apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: resnet
spec:
  protocol: v2
  name: resnet
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - name: example
    componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/video-pipelines-mlserver:resnet-human
          name: resnet
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 4Gi
            limits:
              cpu: '4'
              memory: 4Gi
          env:
            - name: MODEL_VARIANT
              value: resnet18
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: TORCH_HOME
              value: /opt/mlserver/.torch
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "5"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
      replicas: 1
    graph:
      name: resnet
      type: MODEL
      children: []
    svcOrchSpec:
      resources:
        requests:
          cpu: '4'
          memory: 4Gi
        limits:
          cpu: '4'
          memory: 4Gi