apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: nlp
spec:
  name: nlp
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/nlp-pipelines:generalnlp
          name: nlp-1
          imagePullPolicy: Always
          env:
            - name: MODEL_VARIANT
              value: dinalzein/xlm-roberta-base-finetuned-language-identification
            - name: TRANSFORMERS_CACHE
              value: /app/.cache
            - name: TASK
              value: text-classification
    - spec:
        containers:
        - image: sdghafouri/nlp-pipelines:generalnlp
          name: nlp-2
          imagePullPolicy: Always
          env:
            - name: MODEL_VARIANT
              value: Helsinki-NLP/opus-mt-fr-en
            - name: TRANSFORMERS_CACHE
              value: /app/.cache
            - name: TASK
              value: translation_fr_to_en
    - spec:
        containers:
        - image: sdghafouri/nlp-pipelines:generalnlp
          name: nlp-3
          imagePullPolicy: Always
          env:
            - name: MODEL_VARIANT
              value: sshleifer/distilbart-cnn-12-6
            - name: TRANSFORMERS_CACHE
              value: /app/.cache
            - name: TASK
              value: summarization
    graph:
      name: nlp-1
      type: MODEL
      children:
      - name: nlp-2
        type: MODEL
        children:
        - name: nlp-3
          type: MODEL
          children: []
    name: example
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1
