apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: {{ name }}
spec:
  protocol: v2
  name: {{ name }}
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - name: default
    componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/audio-qa-pipelines-mlserver:nlpqa
          name: nlp-qa 
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '{{ cpu_request }}'
              memory: '{{ memory_request }}'
            limits:
              cpu: '{{ cpu_limit }}'
              memory: '{{ memory_limit }}'
          env:
            - name: MODEL_VARIANT
              value: {{ model_vairant }}
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: TASK
              value: question-answering
            - name: CONTEXT
              value: default
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: '{{ max_batch_size }}'
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: '{{ max_batch_time }}'
      replicas: {{ replicas }}
    graph:
      name: nlp-qa
      type: MODEL
      children: []
    svcOrchSpec:
      resources:
        requests:
          cpu: '4'
          memory: 4Gi
        limits:
          cpu: '4'
          memory: 4Gi